SamplePlotFreq = 1;
Spin = 120;
posPlot = [xpm_Nh(100:n),ypm_Nh(100:n),zeros(n-99,1)];
RT_PLOT(posPlot, coordinate, Rm_data_valid_inx, ...
            'SamplePlotFreq', SamplePlotFreq, 'Trail', 'All', ...
            'Position', [9 39 1280 768], 'View', [(100:(Spin/(length(posPlot)-1)):(100+Spin))', 10*ones(length(posPlot), 1)], ...
            'AxisLength', 0.1, 'ShowArrowHead', false, ...
            'Xlabel', 'X (m)', 'Ylabel', 'Y (m)', 'Zlabel', 'Z (m)', 'ShowLegend', false, ...
            'CreateAVI', false, 'AVIfileNameEnum', false, 'AVIfps', ((1/samplePeriod) / SamplePlotFreq));

